services:
  auth:
    depends_on:
      templates-server:
        condition: service_started
    env_file:
      - ./.env.auth
    environment:
      GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI: ${API_EXTERNAL_URL}/callback
      GOTRUE_EXTERNAL_APPLE_REDIRECT_URI: ${API_EXTERNAL_URL}/callback
      GOTRUE_EXTERNAL_GITHUB_REDIRECT_URI: ${API_EXTERNAL_URL}/callback
      GOTRUE_MAILER_OTP_EXP: "900"
      GOTRUE_MAILER_OTP_LENGTH: "6"
      GOTRUE_MAILER_SUBJECTS_CONFIRMATION: Your Organa verification code
      GOTRUE_MAILER_SUBJECTS_MAGIC_LINK: Your Organa verification code
      GOTRUE_MAILER_TEMPLATES_CONFIRMATION: http://templates-server/email-code.html
      GOTRUE_MAILER_TEMPLATES_MAGIC_LINK: http://templates-server/email-code.html

  functions:
    env_file:
      - ./.env.functions

  templates-server:
    image: caddy:2-alpine
    restart: unless-stopped
    command:
      - caddy
      - file-server
      - --root
      - /templates
      - --listen
      - :80
    volumes:
      - ./volumes/templates:/templates:ro
